version: '3.8'

services:
  fake-news-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    
  streamlit-app:
    build: .
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    depends_on:
      - fake-news-api

networks:
  default:
    name: fake-news-network
